export const ALL_CHATS_REQUEST = "ALL_CHATS_REQUEST";
export const ALL_CHATS_SUCCESS = "ALL_CHATS_SUCCESS";
export const ALL_CHATS_FAIL = "ALL_CHATS_FAIL";

export const NEW_CHAT_REQUEST = "NEW_CHAT_REQUEST";
export const NEW_CHAT_SUCCESS = "NEW_CHAT_SUCCESS";
export const NEW_CHAT_RESET = "NEW_CHAT_RESET";
export const NEW_CHAT_FAIL = "NEW_CHAT_FAIL";
export const UPDATE_NAME_CHAT = "UPDATE_NAME_CHAT";
export const UPDATE_AVATAR_CHAT = "UPDATE_AVATAR_CHAT";
export const DELETE_USER_CHAT = "DELETE_USER_CHAT";
export const ADD_USER_CHAT = "ADD_USER_CHAT";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
