// constants/notificationConstants.js
export const GET_NOTIFICATIONS_REQUEST = "GET_NOTIFICATIONS_REQUEST";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_FAIL = "GET_NOTIFICATIONS_FAIL";

export const GET_RECENT_NOTIFICATIONS_REQUEST =
  "GET_RECENT_NOTIFICATIONS_REQUEST";
export const GET_RECENT_NOTIFICATIONS_SUCCESS =
  "GET_RECENT_NOTIFICATIONS_SUCCESS";
export const GET_RECENT_NOTIFICATIONS_FAIL = "GET_RECENT_NOTIFICATIONS_FAIL";

export const GET_UNREAD_COUNT_REQUEST = "GET_UNREAD_COUNT_REQUEST";
export const GET_UNREAD_COUNT_SUCCESS = "GET_UNREAD_COUNT_SUCCESS";
export const GET_UNREAD_COUNT_FAIL = "GET_UNREAD_COUNT_FAIL";

export const MARK_AS_READ_REQUEST = "MARK_AS_READ_REQUEST";
export const MARK_AS_READ_SUCCESS = "MARK_AS_READ_SUCCESS";
export const MARK_AS_READ_FAIL = "MARK_AS_READ_FAIL";

export const MARK_ALL_AS_READ_REQUEST = "MARK_ALL_AS_READ_REQUEST";
export const MARK_ALL_AS_READ_SUCCESS = "MARK_ALL_AS_READ_SUCCESS";
export const MARK_ALL_AS_READ_FAIL = "MARK_ALL_AS_READ_FAIL";

export const DELETE_NOTIFICATION_REQUEST = "DELETE_NOTIFICATION_REQUEST";
export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_FAIL = "DELETE_NOTIFICATION_FAIL";

export const NEW_NOTIFICATION_RECEIVED = "NEW_NOTIFICATION_RECEIVED";

export const CLEAR_NOTIFICATION_ERRORS = "CLEAR_NOTIFICATION_ERRORS";
